version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: olist_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./data:/var/lib/mysql-files
    command: --secure-file-priv=/var/lib/mysql-files

  ansible:
    build: .
    volumes:
      - .:/app
    depends_on:
      - mysql

volumes:
  mysql_data: 