---
- name: Create MySQL Database and Load Data
  hosts: mysql
  become: yes
  tasks:
    - name: Create MySQL database
      mysql_db:
        name: olist_db
        state: present
        login_host: mysql
        login_user: root
        login_password: root

    - name: Drop existing tables
      mysql_query:
        login_host: mysql
        login_user: root
        login_password: root
        db: olist_db
        query: |
          DROP TABLE IF EXISTS orders;
          DROP TABLE IF EXISTS order_items;
          DROP TABLE IF EXISTS order_payments;
          DROP TABLE IF EXISTS order_reviews;
          DROP TABLE IF EXISTS customers;
          DROP TABLE IF EXISTS geolocation;
          DROP TABLE IF EXISTS products;
          DROP TABLE IF EXISTS sellers;
          DROP TABLE IF EXISTS product_category_name_translation;

    - name: Create tables
      mysql_query:
        login_host: mysql
        login_user: root
        login_password: root
        db: olist_db
        query: |
          CREATE TABLE customers (
            customer_id VARCHAR(128) PRIMARY KEY,
            customer_unique_id VARCHAR(128),
            customer_zip_code_prefix VARCHAR(8),
            customer_city VARCHAR(128),
            customer_state CHAR(2)
          );

          CREATE TABLE geolocation (
            geolocation_zip_code_prefix VARCHAR(8),
            geolocation_lat DECIMAL(10,8),
            geolocation_lng DECIMAL(11,8),
            geolocation_city VARCHAR(128),
            geolocation_state CHAR(2)
          );

          CREATE TABLE order_items (
            order_id VARCHAR(128),
            order_item_id INT,
            product_id VARCHAR(128),
            seller_id VARCHAR(128),
            shipping_limit_date DATETIME,
            price DECIMAL(10,2),
            freight_value DECIMAL(10,2),
            PRIMARY KEY (order_id, order_item_id)
          );

          CREATE TABLE order_payments (
            order_id VARCHAR(128),
            payment_sequential INT,
            payment_type VARCHAR(32),
            payment_installments INT,
            payment_value DECIMAL(10,2),
            PRIMARY KEY (order_id, payment_sequential)
          );

          CREATE TABLE order_reviews (
            review_id VARCHAR(128) PRIMARY KEY,
            order_id VARCHAR(128),
            review_score INT,
            review_comment_title TEXT,
            review_comment_message TEXT,
            review_creation_date DATETIME,
            review_answer_timestamp DATETIME
          );

          CREATE TABLE orders (
            order_id VARCHAR(128) PRIMARY KEY,
            customer_id VARCHAR(128),
            order_status VARCHAR(32),
            order_purchase_timestamp DATETIME,
            order_approved_at DATETIME,
            order_delivered_carrier_date DATETIME,
            order_delivered_customer_date DATETIME,
            order_estimated_delivery_date DATETIME,
            FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
          );

          CREATE TABLE products (
            product_id VARCHAR(128) PRIMARY KEY,
            product_category_name VARCHAR(128),
            product_name_length INT,
            product_description_length INT,
            product_photos_qty INT,
            product_weight_g INT,
            product_length_cm INT,
            product_height_cm INT,
            product_width_cm INT
          );

          CREATE TABLE sellers (
            seller_id VARCHAR(128) PRIMARY KEY,
            seller_zip_code_prefix VARCHAR(8),
            seller_city VARCHAR(128),
            seller_state CHAR(2)
          );

          CREATE TABLE product_category_name_translation (
            product_category_name VARCHAR(128) PRIMARY KEY,
            product_category_name_english VARCHAR(128)
          );

    - name: Load CSV data
      mysql_query:
        login_host: mysql
        login_user: root
        login_password: root
        db: olist_db
        query: |
          LOAD DATA INFILE '/var/lib/mysql-files/olist_customers_dataset.csv' INTO TABLE customers FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
          LOAD DATA INFILE '/var/lib/mysql-files/olist_geolocation_dataset.csv' INTO TABLE geolocation FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
          LOAD DATA INFILE '/var/lib/mysql-files/olist_order_items_dataset.csv' INTO TABLE order_items FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
          LOAD DATA INFILE '/var/lib/mysql-files/olist_order_payments_dataset.csv' INTO TABLE order_payments FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
          LOAD DATA INFILE '/var/lib/mysql-files/olist_order_reviews_dataset.csv' INTO TABLE order_reviews FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
          LOAD DATA INFILE '/var/lib/mysql-files/olist_orders_dataset.csv' INTO TABLE orders FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
          LOAD DATA INFILE '/var/lib/mysql-files/olist_products_dataset.csv' INTO TABLE products FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
          LOAD DATA INFILE '/var/lib/mysql-files/olist_sellers_dataset.csv' INTO TABLE sellers FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
          LOAD DATA INFILE '/var/lib/mysql-files/product_category_name_translation.csv' INTO TABLE product_category_name_translation FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;

    - name: Install required packages
      apt:
        name: 
          - mysql-server
          - python3-mysqldb
        state: present
        update_cache: yes

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes 