---
- name: Create MySQL Database
  hosts: mysql
  become: yes
  tasks:
    - name: Create MySQL database
      mysql_db:
        name: olist_db
        state: present
        login_host: mysql
        login_user: root
        login_password: root

    - name: Install required packages
      apt:
        name: 
          - mysql-server
          - python3-mysqldb
        state: present
        update_cache: yes

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes 